// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCDePO1QNQ7zMaDNJ8gLdepFWPLneaijg',
    appId: '1:282076378546:web:d8c4b0ccf9b1ab469160ab',
    messagingSenderId: '282076378546',
    projectId: 'instagram-v2-2d7e4',
    authDomain: 'instagram-v2-2d7e4.firebaseapp.com',
    storageBucket: 'instagram-v2-2d7e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNgs7111X5qmih3LaEhUu975vR38MZfYI',
    appId: '1:282076378546:android:2dbb1894a9175d989160ab',
    messagingSenderId: '282076378546',
    projectId: 'instagram-v2-2d7e4',
    storageBucket: 'instagram-v2-2d7e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3mjPBE5jH8cLPp-T8oOb0xLA2e3dam_0',
    appId: '1:282076378546:ios:7dc06f028ac7e8579160ab',
    messagingSenderId: '282076378546',
    projectId: 'instagram-v2-2d7e4',
    storageBucket: 'instagram-v2-2d7e4.appspot.com',
    iosClientId: '282076378546-ohqq73hkgcg9ek26rbqsgg7dmdussajc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram.v2',
  );
}
